### ISSUE TITLE
How to setTimeout?

### ISSUE THREAD

**Issue by Ben-Mack** [verseles/flyclone#4]
Hi, thank you for this helpful lib!

The default 120s timeout, 100s idleTimeout is not enough for my use case, how can I set custom timeout without modify the library core?
Currently there's only one method for `setIdleTimeout`, please add `setTimeout` method.

**Comment by insign** [comment]
Thank you, I added new getters and setters, check this out!

**Comment by Ben-Mack** [comment]
God speed!! Thank you 🥇

**Comment by insign** [comment]
Don't forget do run `composer update` to get v0.20

**Comment by Ben-Mack** [comment]
Hi @insign, is it possible to set minimum PHP supported to 7.4?
That's the latest PHP version on my server, PHP 8 only seems too restricted

**Comment by insign** [comment]
I think I can but I need to test before. Can you do that?

**Comment by Ben-Mack** [comment]
Sorry, I'm pretty new in PHP land

**Comment by Ben-Mack** [comment]
What should I do?
